server:
  servlet:
    context-path: /auto-escola/api

spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://autoescola.postgres.uhserver.com:5432/autoescola
    username: rlti
    password: Dev@8524*
  jpa:
    generate-ddl: true
    properties:
      hibernate:
        ddl-auto: update
        show_sql: true
        format_sql: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 1MB
      max-request-size: 1MB
      file-size-threshold: 0
      location: ~/temp/

springdoc:
  swagger-ui:
    path: /public/swagger