spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE}
server:
  servlet:
    context-path: /auto-escola/api
    multipart:
      enabled: true
      max-file-size: 1MB
      max-request-size: 1MB
      file-size-threshold: 0
      location: ~/temp/

springdoc:
  swagger-ui:
    path: /public/swagger