spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE}
server:
  servlet:
    context-path: /auto-escola/api
    multipart:
      enabled: true
      max-file-size: 1MB
      max-request-size: 1MB
      file-size-threshold: 0
      location: ~/temp/

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 3600000 # 60 MINUTOS
      refresh-token:
        expiration: 3600000 # 60 MINUTOS

springdoc:
  swagger-ui:
    path: /public/swagger